// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function SaveFile(data) {
    return $Call.ByID(4188964126, data);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function UploadFile() {
    return $Call.ByID(3228067530);
}
