// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class FEC {
    /**
     * Creates a new FEC instance.
     * @param {Partial<FEC>} [$$source = {}] - The source object to create the FEC.
     */
    constructor($$source = {}) {
        if (!("PreFEC" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["PreFEC"] = "";
        }
        if (!("Q_Factor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Q_Factor"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FEC instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FEC}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FEC(/** @type {Partial<FEC>} */($$parsedSource));
    }
}
