// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} scriptPath
 * @returns {$CancellablePromise<$models.Script>}
 */
export function GetScriptContent(scriptPath) {
    return $Call.ByID(312704369, scriptPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} folder
 * @returns {$CancellablePromise<string[]>}
 */
export function GetScriptsList(folder) {
    return $Call.ByID(3492310065, folder).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.SSHService | null} sshService
 * @returns {$CancellablePromise<void>}
 */
export function Run(sshService) {
    return $Call.ByID(3528865246, sshService);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function SelectFolder() {
    return $Call.ByID(1009339561);
}

// Private type creation functions
const $$createType0 = $models.Script.createFrom;
const $$createType1 = $Create.Array($Create.Any);
